### ISSUE TITLE
Cannot import a wallet + TypeError: Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp-lite#26]
Steps: 

1. I tried to open my old wallet with 12 words (I put them correctly)
2. then I got the password setup screen- completed successfully
3. the app just moved back to the main page
4. after leaving it idle in the background for a moment, I had a login page
5.  I put the correct password and got this
![Screenshot 2024-07-04 at 23 01 40](https://github.com/spacemeshos/smapp-lite/assets/89876259/008498c4-d538-4386-8c73-01778382f9cb)

Unexpected Application Error!
Cannot convert undefined to a BigInt
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at convertSpawnArgumentsForEncoding (http://localhost:5173/src/utils/templates.ts:69:17)
    at computeAddress (http://localhost:5173/src/utils/wallet.ts:80:16)
    at http://localhost:5173/src/hooks/useWalletSelectors.ts:12:16
    at Array.map (<anonymous>)
    at http://localhost:5173/src/hooks/useWalletSelectors.ts:10:21
    at mountMemo (http://localhost:5173/node_modules/.vite/deps/chunk-ZRNALROW.js?v=b9c8e656:12214:27)
    at Object.useMemo (http://localhost:5173/node_modules/.vite/deps/chunk-ZRNALROW.js?v=b9c8e656:12538:24)
    at useMemo (http://localhost:5173/node_modules/.vite/deps/chunk-LXGCQ6UQ.js?v=b9c8e656:1094:29)
    at useAccountsList (http://localhost:5173/src/hooks/useWalletSelectors.ts:8:10)

**Comment by brusherru** [comment]
Not actual anymore
